### ISSUE TITLE
Release v1.3.0

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/ccao#7]
Cut a new release of the package containing [the following changes](https://github.com/ccao-data/ccao/compare/1.2.2...8b4ed8409a580d1aae54cf00e44bb759bc3fa483):

* Add pre-commit badge (https://github.com/ccao-data/ccao/commit/4b9688c70d6e6cc9ce2f8489fc7c417b794057a2)
* Deploy to GitHub pages (https://github.com/ccao-data/ccao/commit/c559f46192c48365bc218ef7cff6fdc405a97851)
* Add core team to CODEOWNERS (#1)
* Add `meta_card_protation_rate` and `loc_tax_municipality_name` to `vars_dict` (#4)
* Update authors and add docs to sidebar (#5)
* Consolidate `vars_dict` to focus exclusively on renaming/recoding (#6)

## Release checklist

- [x] Make sure the changes meet styling and linting requirements:
  - *Styling*: Run `styler::style_pkg()` in the console
  - *Linting*: Run `lintr::lint_package()` in the console
- [x] Build any documentation updates by running `devtools::document()` in the console
- [x] Run the build and test processes locally to check for errors:
  - *Build*: In RStudio, go to the **Build** tab, then hit **Check**
  - *Test*: In RStudio, go to the **Build** tab, then hit **Test** OR `devtools::test()` in the console
- [x] Check the vignettes by building them locally. Run `pkgdown::build_site()` in the console
- [x] Rebuild the README manually. Knit `README.Rmd` from within RStudio
- [x] Increment the package version in the `DESCRIPTION` file appropriately, following the schema laid out in the README
- [x] If the code updates were so substantial that the current database also needs to be updated, follow the database release checklist issue template
- [x] Push the code updates to GitHub. Wait for the resulting CI pipeline to finish
- [x] If there are no pipeline errors, merge the branch to master
- [x] Wait for the merge CI pipeline to finish. If there are no errors, cut a new release from master. Create a new git tag with the version number and title the release with the same version number. Be sure to add a changelog detailing what you updated

**Comment by dfsnow** [comment]
Closed by c6190e35da9169c1246cd0305dfeae98d265db08.
